'use client'

import { createContext, useContext, useEffect, useState } from 'react'

export type Idioma = 'pt' | 'en' | 'es' | 'fr' | 'ar' | 'ja'

export const IDIOMAS = [
  { id: 'pt', label: 'Português', flag: '🇧🇷' },
  { id: 'en', label: 'English',   flag: '🇺🇸' },
  { id: 'es', label: 'Español',   flag: '🇪🇸' },
  { id: 'fr', label: 'Français',  flag: '🇫🇷' },
  { id: 'ar', label: 'العربية',   flag: '🇸🇦' },
  { id: 'ja', label: '日本語',     flag: '🇯🇵' },
]

export const TRADUCOES: Record<Idioma, Record<string, string>> = {
  // ─────────────────────────────── PORTUGUÊS ───────────────────────────────
  pt: {
    // Nav / geral
    painel: 'Painel', agendamentos: 'Agendamentos', servicos: 'Serviços',
    profissionais: 'Profissionais', clientes: 'Clientes', faturamento: 'Faturamento',
    configuracoes: 'Configurações', sair: 'Sair', copiarLink: 'Copiar link',
    estabelecimento: 'Estabelecimento', voltar: '← Voltar', carregando: 'Carregando...',
    excluir: 'Excluir', cancelar: 'Cancelar', confirmar: 'Confirmar', cancelarAcao: 'Cancelar',
    salvando: 'Salvando...',
    // Configurações
    salvar: 'Salvar configurações', sucesso: '✓ Configurações salvas com sucesso!',
    infoBasicas: 'Informações básicas', horarioFunc: 'Horário de funcionamento',
    aparencia: 'Aparência e idioma', modoEscuro: 'Modo escuro', idioma: 'Idioma',
    nomeEstab: 'Nome do estabelecimento', linkAgend: 'Link de agendamento',
    telefone: 'Telefone', descricao: 'Descrição', diasAtend: 'Dias de atendimento',
    abertura: 'Abertura', fechamento: 'Fechamento',
    // Serviços
    servicosSubtitle: 'Gerencie os serviços do seu estabelecimento',
    novoServico: '+ Novo serviço', novoServicoTitulo: 'Novo serviço',
    nomeServico: 'Nome do serviço *', descricaoOpcional: 'Descrição',
    duracaoLabel: 'Duração *', precoLabel: 'Preço (R$) *',
    placeholderServico: 'Ex: Corte de cabelo', placeholderDescricao: 'Descrição opcional',
    placeholderPreco: 'Ex: 50,00', salvarServico: 'Salvar serviço',
    nenhumServico: 'Nenhum serviço cadastrado',
    nenhumServicoDesc: 'Clique em "Novo serviço" para adicionar.',
    erroPreencherCampos: 'Preencha todos os campos obrigatórios.',
    erroConfigurarEstab: 'Configure seu estabelecimento primeiro.',
    erroSalvarServico: 'Erro ao salvar serviço.',
    // Profissionais
    profissionaisSubtitle: 'Gerencie a equipe do seu estabelecimento',
    novoProfissional: '+ Novo profissional', novoProfissionalTitulo: 'Novo profissional',
    foto: 'Foto', fotoCliqueAdicionar: 'Clique para adicionar', fotoRemover: 'Remover',
    nomeLabel: 'Nome *', descricaoVisivelCliente: 'Descrição',
    descricaoVisivelClienteHint: '— visível para o cliente',
    salvarProfissional: 'Salvar profissional',
    nenhumProfissional: 'Nenhum profissional cadastrado',
    nenhumProfissionalDesc: 'Clique em "+ Novo profissional" para adicionar.',
    semDescricao: 'Sem descrição',
    fotoAdicionada: '✓ Foto adicionada · clique no avatar para trocar',
    cliqueFoto: 'Clique no avatar para adicionar foto',
    cliqueTrocarFoto: 'Clique para trocar a foto',
    erroNomeProfissional: 'Digite o nome do profissional.',
    erroEnviarFoto: 'Erro ao enviar foto: ', erroSalvarFoto: 'Erro ao salvar foto: ',
    confirmarExcluir: 'Tem certeza que deseja excluir este profissional?',
    // Dashboard
    planoAtivadoTitulo: 'Plano Pro ativado com sucesso!',
    planoAtivadoDesc: 'Agendamentos ilimitados liberados. Aproveite!',
    limiteAtingido: 'Você atingiu o limite do plano gratuito',
    agendamentosRestantes: 'Você tem {n} agendamento(s) gratuito(s) restantes',
    assinarDesc: 'Assine o plano Pro por <strong style="color:#00C27C">R$49,90/mês</strong> e tenha agendamentos ilimitados',
    assinarAgora: '💳 Assinar agora — R$49,90/mês', redirecionando: 'Redirecionando...',
    planoProAtivo: 'Plano Pro ativo',
    ola: 'Olá, {nome}! 👋', bemVindo: 'Bem-vindo! 👋',
    resumoHoje: 'Aqui está um resumo do seu estabelecimento hoje.',
    agendamentosHoje: 'Agendamentos hoje', clientesCadastrados: 'Clientes cadastrados',
    faturamentoMes: 'Faturamento do mês', aguardandoConfirmacao: 'Aguardando confirmação',
    seuLink: 'Seu link de agendamento', linkCopiado: 'Link copiado!',
    copiar: 'Copiar', verPagina: 'Ver página',
    // Agendamentos
    agendamentosSubtitle: 'Gerencie todos os agendamentos do seu estabelecimento',
    filtroTodos: 'Todos', filtroPendentes: 'Pendentes', filtroConfirmados: 'Confirmados',
    filtroConcluidos: 'Concluídos', filtroCancelados: 'Cancelados',
    nenhumAgendamento: 'Nenhum agendamento',
    nenhumAgendamentoDesc: 'Compartilhe seu link para começar a receber agendamentos.',
    concluir: 'Concluir', as: 'às',
    pgDinheiro: 'Dinheiro', pgPix: 'Pix', pgCartao: 'Cartão',
    confirmarExcluirAgend: 'Tem certeza que deseja excluir este agendamento?',
        confirmarExcluirAgendFaturamento: 'Este agendamento será excluído e o valor será descontado do faturamento. Confirma?',
    // Clientes
    buscarCliente: 'Buscar cliente...', clienteSingular: 'cliente', clientePlural: 'clientes',
    clientesCadastradosLabel: 'cadastrado(s)', nenhumClienteEncontrado: 'Nenhum cliente encontrado',
    nenhumClienteEncontradoDesc: 'Tente buscar por outro nome ou e-mail.',
    nenhumClienteAinda: 'Nenhum cliente ainda',
    nenhumClienteAindaDesc: 'Os clientes aparecerão aqui quando realizarem agendamentos.',
    agendamentoSingular: 'agendamento', agendamentoPlural: 'agendamentos', gastos: 'gastos',
        confirmarExcluirCliente: 'Tem certeza que deseja excluir o cliente "{nome}"?',
    // Faturamento
    faturamentoSubtitle: 'Acompanhe sua receita mês a mês',
    total12Meses: 'Total nos últimos 12 meses', melhorMes: 'Melhor mês', vsMesAnterior: 'Vs. mês anterior',
    faturamentoPorMes: 'Faturamento por mês',
    legendaSelecionado: 'Selecionado', legendaMesAtual: 'Mês atual', legendaMesesAnteriores: 'Meses anteriores',
    pagamentosMes: 'Pagamentos — {mes}', pagamentosMesDesc: 'Como os clientes pagaram neste mês',
    pagamentosGeral: 'Pagamentos — Últimos 12 meses', pagamentosGeralDesc: 'Visão geral de todas as formas de pagamento',
    semPagamentosMes: 'Sem pagamentos neste mês.', semPagamentosGeral: 'Sem pagamentos registrados.',
    semDados: 'Sem dados', pagamentos: 'pag.',
    agendamentosConcluidos: 'agendamento(s) concluído(s)', totalDoMes: 'Total do mês',
    nenhumAgendamentoConcluido: 'Nenhum agendamento concluído neste mês.',
    totalServicos: 'Total de {n} serviço(s):',
    pgOutro: 'Outros',
    mesJan: 'Jan', mesFev: 'Fev', mesMar: 'Mar', mesAbr: 'Abr', mesMai: 'Mai', mesJun: 'Jun',
    mesJul: 'Jul', mesAgo: 'Ago', mesSet: 'Set', mesOut: 'Out', mesNov: 'Nov', mesDez: 'Dez',
    mesJanL: 'Janeiro', mesFevL: 'Fevereiro', mesMarL: 'Março', mesAbrL: 'Abril', mesMaiL: 'Maio', mesJunL: 'Junho',
    mesJulL: 'Julho', mesAgoL: 'Agosto', mesSetL: 'Setembro', mesOutL: 'Outubro', mesNovL: 'Novembro', mesDezL: 'Dezembro',
  },

  // ─────────────────────────────── ENGLISH ────────────────────────────────
  en: {
    painel: 'Dashboard', agendamentos: 'Appointments', servicos: 'Services',
    profissionais: 'Professionals', clientes: 'Clients', faturamento: 'Revenue',
    configuracoes: 'Settings', sair: 'Logout', copiarLink: 'Copy link',
    estabelecimento: 'Business', voltar: '← Back', carregando: 'Loading...',
    excluir: 'Delete', cancelar: 'Cancel', confirmar: 'Confirm', cancelarAcao: 'Cancel',
    salvando: 'Saving...',
    salvar: 'Save settings', sucesso: '✓ Settings saved successfully!',
    infoBasicas: 'Basic information', horarioFunc: 'Business hours',
    aparencia: 'Appearance & language', modoEscuro: 'Dark mode', idioma: 'Language',
    nomeEstab: 'Business name', linkAgend: 'Booking link',
    telefone: 'Phone', descricao: 'Description', diasAtend: 'Working days',
    abertura: 'Opening', fechamento: 'Closing',
    servicosSubtitle: 'Manage your business services',
    novoServico: '+ New service', novoServicoTitulo: 'New service',
    nomeServico: 'Service name *', descricaoOpcional: 'Description',
    duracaoLabel: 'Duration *', precoLabel: 'Price *',
    placeholderServico: 'e.g. Haircut', placeholderDescricao: 'Optional description',
    placeholderPreco: 'e.g. 50.00', salvarServico: 'Save service',
    nenhumServico: 'No services registered',
    nenhumServicoDesc: 'Click "New service" to add one.',
    erroPreencherCampos: 'Please fill in all required fields.',
    erroConfigurarEstab: 'Set up your business first.',
    erroSalvarServico: 'Error saving service.',
    profissionaisSubtitle: 'Manage your team',
    novoProfissional: '+ New professional', novoProfissionalTitulo: 'New professional',
    foto: 'Photo', fotoCliqueAdicionar: 'Click to add', fotoRemover: 'Remove',
    nomeLabel: 'Name *', descricaoVisivelCliente: 'Description',
    descricaoVisivelClienteHint: '— visible to clients',
    salvarProfissional: 'Save professional',
    nenhumProfissional: 'No professionals registered',
    nenhumProfissionalDesc: 'Click "+ New professional" to add one.',
    semDescricao: 'No description',
    fotoAdicionada: '✓ Photo added · click avatar to change',
    cliqueFoto: 'Click avatar to add photo', cliqueTrocarFoto: 'Click to change photo',
    erroNomeProfissional: "Enter the professional's name.",
    erroEnviarFoto: 'Error uploading photo: ', erroSalvarFoto: 'Error saving photo: ',
    confirmarExcluir: 'Are you sure you want to delete this professional?',
    planoAtivadoTitulo: 'Pro plan activated successfully!',
    planoAtivadoDesc: 'Unlimited appointments unlocked. Enjoy!',
    limiteAtingido: 'You have reached the free plan limit',
    agendamentosRestantes: 'You have {n} free appointment(s) remaining',
    assinarDesc: 'Subscribe to the Pro plan for <strong style="color:#00C27C">R$49.90/mo</strong> and get unlimited appointments',
    assinarAgora: '💳 Subscribe now — R$49.90/mo', redirecionando: 'Redirecting...',
    planoProAtivo: 'Pro plan active',
    ola: 'Hello, {nome}! 👋', bemVindo: 'Welcome! 👋',
    resumoHoje: "Here's a summary of your business today.",
    agendamentosHoje: "Today's appointments", clientesCadastrados: 'Registered clients',
    faturamentoMes: "This month's revenue", aguardandoConfirmacao: 'Awaiting confirmation',
    seuLink: 'Your booking link', linkCopiado: 'Link copied!',
    copiar: 'Copy', verPagina: 'View page',
    agendamentosSubtitle: 'Manage all appointments for your business',
    filtroTodos: 'All', filtroPendentes: 'Pending', filtroConfirmados: 'Confirmed',
    filtroConcluidos: 'Completed', filtroCancelados: 'Cancelled',
    nenhumAgendamento: 'No appointments',
    nenhumAgendamentoDesc: 'Share your link to start receiving appointments.',
    concluir: 'Complete', as: 'at',
    pgDinheiro: 'Cash', pgPix: 'Pix', pgCartao: 'Card',
    confirmarExcluirAgend: 'Are you sure you want to delete this appointment?',
        confirmarExcluirAgendFaturamento: 'This appointment will be deleted and the amount deducted from revenue. Confirm?',
    // Clientes
    buscarCliente: 'Search client...', clienteSingular: 'client', clientePlural: 'clients',
    clientesCadastradosLabel: 'registered', nenhumClienteEncontrado: 'No client found',
    nenhumClienteEncontradoDesc: 'Try searching by another name or email.',
    nenhumClienteAinda: 'No clients yet',
    nenhumClienteAindaDesc: 'Clients will appear here when they make appointments.',
    agendamentoSingular: 'appointment', agendamentoPlural: 'appointments', gastos: 'spent',
        confirmarExcluirCliente: 'Are you sure you want to delete client "{nome}"?',
    // Faturamento
    faturamentoSubtitle: 'Track your revenue month by month',
    total12Meses: 'Total last 12 months', melhorMes: 'Best month', vsMesAnterior: 'Vs. previous month',
    faturamentoPorMes: 'Revenue by month',
    legendaSelecionado: 'Selected', legendaMesAtual: 'Current month', legendaMesesAnteriores: 'Previous months',
    pagamentosMes: 'Payments — {mes}', pagamentosMesDesc: 'How clients paid this month',
    pagamentosGeral: 'Payments — Last 12 months', pagamentosGeralDesc: 'Overview of all payment methods',
    semPagamentosMes: 'No payments this month.', semPagamentosGeral: 'No payments recorded.',
    semDados: 'No data', pagamentos: 'pay.',
    agendamentosConcluidos: 'completed appointment(s)', totalDoMes: 'Month total',
    nenhumAgendamentoConcluido: 'No completed appointments this month.',
    totalServicos: 'Total of {n} service(s):',
    pgOutro: 'Other',
    mesJan: 'Jan', mesFev: 'Feb', mesMar: 'Mar', mesAbr: 'Apr', mesMai: 'May', mesJun: 'Jun',
    mesJul: 'Jul', mesAgo: 'Aug', mesSet: 'Sep', mesOut: 'Oct', mesNov: 'Nov', mesDez: 'Dec',
    mesJanL: 'January', mesFevL: 'February', mesMarL: 'March', mesAbrL: 'April', mesMaiL: 'May', mesJunL: 'June',
    mesJulL: 'July', mesAgoL: 'August', mesSetL: 'September', mesOutL: 'October', mesNovL: 'November', mesDezL: 'December',
  },

  // ─────────────────────────────── ESPAÑOL ────────────────────────────────
  es: {
    painel: 'Panel', agendamentos: 'Citas', servicos: 'Servicios',
    profissionais: 'Profesionales', clientes: 'Clientes', faturamento: 'Facturación',
    configuracoes: 'Configuración', sair: 'Salir', copiarLink: 'Copiar enlace',
    estabelecimento: 'Negocio', voltar: '← Volver', carregando: 'Cargando...',
    excluir: 'Eliminar', cancelar: 'Cancelar', confirmar: 'Confirmar', cancelarAcao: 'Cancelar',
    salvando: 'Guardando...',
    salvar: 'Guardar configuración', sucesso: '✓ ¡Configuración guardada con éxito!',
    infoBasicas: 'Información básica', horarioFunc: 'Horario de atención',
    aparencia: 'Apariencia e idioma', modoEscuro: 'Modo oscuro', idioma: 'Idioma',
    nomeEstab: 'Nombre del negocio', linkAgend: 'Enlace de reserva',
    telefone: 'Teléfono', descricao: 'Descripción', diasAtend: 'Días de atención',
    abertura: 'Apertura', fechamento: 'Cierre',
    servicosSubtitle: 'Administra los servicios de tu negocio',
    novoServico: '+ Nuevo servicio', novoServicoTitulo: 'Nuevo servicio',
    nomeServico: 'Nombre del servicio *', descricaoOpcional: 'Descripción',
    duracaoLabel: 'Duración *', precoLabel: 'Precio *',
    placeholderServico: 'Ej: Corte de cabello', placeholderDescricao: 'Descripción opcional',
    placeholderPreco: 'Ej: 50,00', salvarServico: 'Guardar servicio',
    nenhumServico: 'Sin servicios registrados',
    nenhumServicoDesc: 'Haz clic en "Nuevo servicio" para agregar.',
    erroPreencherCampos: 'Completa todos los campos obligatorios.',
    erroConfigurarEstab: 'Configura tu negocio primero.',
    erroSalvarServico: 'Error al guardar el servicio.',
    profissionaisSubtitle: 'Administra tu equipo',
    novoProfissional: '+ Nuevo profesional', novoProfissionalTitulo: 'Nuevo profesional',
    foto: 'Foto', fotoCliqueAdicionar: 'Clic para agregar', fotoRemover: 'Eliminar',
    nomeLabel: 'Nombre *', descricaoVisivelCliente: 'Descripción',
    descricaoVisivelClienteHint: '— visible para el cliente',
    salvarProfissional: 'Guardar profesional',
    nenhumProfissional: 'Sin profesionales registrados',
    nenhumProfissionalDesc: 'Haz clic en "+ Nuevo profesional" para agregar.',
    semDescricao: 'Sin descripción',
    fotoAdicionada: '✓ Foto agregada · clic en avatar para cambiar',
    cliqueFoto: 'Clic en el avatar para agregar foto', cliqueTrocarFoto: 'Clic para cambiar la foto',
    erroNomeProfissional: 'Ingresa el nombre del profesional.',
    erroEnviarFoto: 'Error al subir foto: ', erroSalvarFoto: 'Error al guardar foto: ',
    confirmarExcluir: '¿Estás seguro de que deseas eliminar este profesional?',
    planoAtivadoTitulo: '¡Plan Pro activado con éxito!',
    planoAtivadoDesc: '¡Citas ilimitadas desbloqueadas. Disfrútalo!',
    limiteAtingido: 'Has alcanzado el límite del plan gratuito',
    agendamentosRestantes: 'Te quedan {n} cita(s) gratuita(s)',
    assinarDesc: 'Suscríbete al plan Pro por <strong style="color:#00C27C">R$49,90/mes</strong> y obtén citas ilimitadas',
    assinarAgora: '💳 Suscribirse ahora — R$49,90/mes', redirecionando: 'Redirigiendo...',
    planoProAtivo: 'Plan Pro activo',
    ola: '¡Hola, {nome}! 👋', bemVindo: '¡Bienvenido! 👋',
    resumoHoje: 'Aquí tienes un resumen de tu negocio hoy.',
    agendamentosHoje: 'Citas hoy', clientesCadastrados: 'Clientes registrados',
    faturamentoMes: 'Facturación del mes', aguardandoConfirmacao: 'Esperando confirmación',
    seuLink: 'Tu enlace de reserva', linkCopiado: '¡Enlace copiado!',
    copiar: 'Copiar', verPagina: 'Ver página',
    agendamentosSubtitle: 'Gestiona todas las citas de tu negocio',
    filtroTodos: 'Todos', filtroPendentes: 'Pendientes', filtroConfirmados: 'Confirmados',
    filtroConcluidos: 'Completados', filtroCancelados: 'Cancelados',
    nenhumAgendamento: 'Sin citas',
    nenhumAgendamentoDesc: 'Comparte tu enlace para empezar a recibir citas.',
    concluir: 'Completar', as: 'a las',
    pgDinheiro: 'Efectivo', pgPix: 'Pix', pgCartao: 'Tarjeta',
    confirmarExcluirAgend: '¿Estás seguro de que deseas eliminar esta cita?',
        confirmarExcluirAgendFaturamento: 'Esta cita se eliminará y el monto se descontará de la facturación. ¿Confirmas?',
    // Clientes
    buscarCliente: 'Buscar cliente...', clienteSingular: 'cliente', clientePlural: 'clientes',
    clientesCadastradosLabel: 'registrado(s)', nenhumClienteEncontrado: 'Sin resultados',
    nenhumClienteEncontradoDesc: 'Prueba buscando por otro nombre o correo.',
    nenhumClienteAinda: 'Sin clientes aún',
    nenhumClienteAindaDesc: 'Los clientes aparecerán aquí cuando realicen citas.',
    agendamentoSingular: 'cita', agendamentoPlural: 'citas', gastos: 'gastados',
        confirmarExcluirCliente: '¿Estás seguro de que deseas eliminar al cliente "{nome}"?',
    // Faturamento
    faturamentoSubtitle: 'Sigue tus ingresos mes a mes',
    total12Meses: 'Total últimos 12 meses', melhorMes: 'Mejor mes', vsMesAnterior: 'Vs. mes anterior',
    faturamentoPorMes: 'Facturación por mes',
    legendaSelecionado: 'Seleccionado', legendaMesAtual: 'Mes actual', legendaMesesAnteriores: 'Meses anteriores',
    pagamentosMes: 'Pagos — {mes}', pagamentosMesDesc: 'Cómo pagaron los clientes este mes',
    pagamentosGeral: 'Pagos — Últimos 12 meses', pagamentosGeralDesc: 'Resumen de todos los métodos de pago',
    semPagamentosMes: 'Sin pagos este mes.', semPagamentosGeral: 'Sin pagos registrados.',
    semDados: 'Sin datos', pagamentos: 'pag.',
    agendamentosConcluidos: 'cita(s) completada(s)', totalDoMes: 'Total del mes',
    nenhumAgendamentoConcluido: 'Ninguna cita completada este mes.',
    totalServicos: 'Total de {n} servicio(s):',
    pgOutro: 'Otros',
    mesJan: 'Ene', mesFev: 'Feb', mesMar: 'Mar', mesAbr: 'Abr', mesMai: 'May', mesJun: 'Jun',
    mesJul: 'Jul', mesAgo: 'Ago', mesSet: 'Sep', mesOut: 'Oct', mesNov: 'Nov', mesDez: 'Dic',
    mesJanL: 'Enero', mesFevL: 'Febrero', mesMarL: 'Marzo', mesAbrL: 'Abril', mesMaiL: 'Mayo', mesJunL: 'Junio',
    mesJulL: 'Julio', mesAgoL: 'Agosto', mesSetL: 'Septiembre', mesOutL: 'Octubre', mesNovL: 'Noviembre', mesDezL: 'Diciembre',
  },

  // ─────────────────────────────── FRANÇAIS ───────────────────────────────
  fr: {
    painel: 'Tableau de bord', agendamentos: 'Rendez-vous', servicos: 'Services',
    profissionais: 'Professionnels', clientes: 'Clients', faturamento: 'Facturation',
    configuracoes: 'Paramètres', sair: 'Déconnexion', copiarLink: 'Copier le lien',
    estabelecimento: 'Établissement', voltar: '← Retour', carregando: 'Chargement...',
    excluir: 'Supprimer', cancelar: 'Annuler', confirmar: 'Confirmer', cancelarAcao: 'Annuler',
    salvando: 'Enregistrement...',
    salvar: 'Enregistrer', sucesso: '✓ Paramètres enregistrés avec succès!',
    infoBasicas: 'Informations de base', horarioFunc: "Heures d'ouverture",
    aparencia: 'Apparence et langue', modoEscuro: 'Mode sombre', idioma: 'Langue',
    nomeEstab: "Nom de l'établissement", linkAgend: 'Lien de réservation',
    telefone: 'Téléphone', descricao: 'Description', diasAtend: 'Jours de travail',
    abertura: 'Ouverture', fechamento: 'Fermeture',
    servicosSubtitle: 'Gérez les services de votre établissement',
    novoServico: '+ Nouveau service', novoServicoTitulo: 'Nouveau service',
    nomeServico: 'Nom du service *', descricaoOpcional: 'Description',
    duracaoLabel: 'Durée *', precoLabel: 'Prix *',
    placeholderServico: 'Ex: Coupe de cheveux', placeholderDescricao: 'Description optionnelle',
    placeholderPreco: 'Ex: 50,00', salvarServico: 'Enregistrer le service',
    nenhumServico: 'Aucun service enregistré',
    nenhumServicoDesc: 'Cliquez sur "Nouveau service" pour en ajouter.',
    erroPreencherCampos: 'Remplissez tous les champs obligatoires.',
    erroConfigurarEstab: "Configurez d'abord votre établissement.",
    erroSalvarServico: "Erreur lors de l'enregistrement du service.",
    profissionaisSubtitle: 'Gérez votre équipe',
    novoProfissional: '+ Nouveau professionnel', novoProfissionalTitulo: 'Nouveau professionnel',
    foto: 'Photo', fotoCliqueAdicionar: 'Cliquez pour ajouter', fotoRemover: 'Supprimer',
    nomeLabel: 'Nom *', descricaoVisivelCliente: 'Description',
    descricaoVisivelClienteHint: '— visible par le client',
    salvarProfissional: 'Enregistrer le professionnel',
    nenhumProfissional: 'Aucun professionnel enregistré',
    nenhumProfissionalDesc: 'Cliquez sur "+ Nouveau professionnel" pour en ajouter.',
    semDescricao: 'Sans description',
    fotoAdicionada: "✓ Photo ajoutée · cliquez sur l'avatar pour changer",
    cliqueFoto: "Cliquez sur l'avatar pour ajouter une photo", cliqueTrocarFoto: 'Cliquez pour changer la photo',
    erroNomeProfissional: 'Entrez le nom du professionnel.',
    erroEnviarFoto: 'Erreur lors du téléchargement: ', erroSalvarFoto: "Erreur lors de l'enregistrement: ",
    confirmarExcluir: 'Êtes-vous sûr de vouloir supprimer ce professionnel?',
    planoAtivadoTitulo: 'Plan Pro activé avec succès !',
    planoAtivadoDesc: 'Rendez-vous illimités débloqués. Profitez-en !',
    limiteAtingido: 'Vous avez atteint la limite du plan gratuit',
    agendamentosRestantes: 'Il vous reste {n} rendez-vous gratuit(s)',
    assinarDesc: 'Abonnez-vous au plan Pro pour <strong style="color:#00C27C">R$49,90/mois</strong> et obtenez des rendez-vous illimités',
    assinarAgora: "💳 S'abonner — R$49,90/mois", redirecionando: 'Redirection...',
    planoProAtivo: 'Plan Pro actif',
    ola: 'Bonjour, {nome} ! 👋', bemVindo: 'Bienvenue ! 👋',
    resumoHoje: "Voici un résumé de votre établissement aujourd'hui.",
    agendamentosHoje: "Rendez-vous aujourd'hui", clientesCadastrados: 'Clients enregistrés',
    faturamentoMes: "Chiffre d'affaires du mois", aguardandoConfirmacao: 'En attente de confirmation',
    seuLink: 'Votre lien de réservation', linkCopiado: 'Lien copié !',
    copiar: 'Copier', verPagina: 'Voir la page',
    agendamentosSubtitle: 'Gérez tous les rendez-vous de votre établissement',
    filtroTodos: 'Tous', filtroPendentes: 'En attente', filtroConfirmados: 'Confirmés',
    filtroConcluidos: 'Terminés', filtroCancelados: 'Annulés',
    nenhumAgendamento: 'Aucun rendez-vous',
    nenhumAgendamentoDesc: 'Partagez votre lien pour commencer à recevoir des rendez-vous.',
    concluir: 'Terminer', as: 'à',
    pgDinheiro: 'Espèces', pgPix: 'Pix', pgCartao: 'Carte',
    confirmarExcluirAgend: 'Êtes-vous sûr de vouloir supprimer ce rendez-vous ?',
        confirmarExcluirAgendFaturamento: "Ce rendez-vous sera supprimé et le montant déduit du chiffre d'affaires. Confirmez ?",
    // Clientes
    buscarCliente: 'Rechercher un client...', clienteSingular: 'client', clientePlural: 'clients',
    clientesCadastradosLabel: 'enregistré(s)', nenhumClienteEncontrado: 'Aucun client trouvé',
    nenhumClienteEncontradoDesc: 'Essayez de rechercher par un autre nom ou email.',
    nenhumClienteAinda: 'Aucun client encore',
    nenhumClienteAindaDesc: 'Les clients apparaîtront ici lorsqu\'ils prendront des rendez-vous.',
    agendamentoSingular: 'rendez-vous', agendamentoPlural: 'rendez-vous', gastos: 'dépensés',
        confirmarExcluirCliente: 'Êtes-vous sûr de vouloir supprimer le client "{nome}" ?',
    // Faturamento
    faturamentoSubtitle: 'Suivez vos revenus mois par mois',
    total12Meses: 'Total 12 derniers mois', melhorMes: 'Meilleur mois', vsMesAnterior: 'Vs. mois précédent',
    faturamentoPorMes: 'Chiffre d\'affaires par mois',
    legendaSelecionado: 'Sélectionné', legendaMesAtual: 'Mois en cours', legendaMesesAnteriores: 'Mois précédents',
    pagamentosMes: 'Paiements — {mes}', pagamentosMesDesc: 'Comment les clients ont payé ce mois',
    pagamentosGeral: 'Paiements — 12 derniers mois', pagamentosGeralDesc: 'Vue d\'ensemble des moyens de paiement',
    semPagamentosMes: 'Aucun paiement ce mois.', semPagamentosGeral: 'Aucun paiement enregistré.',
    semDados: 'Pas de données', pagamentos: 'paiem.',
    agendamentosConcluidos: 'rendez-vous terminé(s)', totalDoMes: 'Total du mois',
    nenhumAgendamentoConcluido: 'Aucun rendez-vous terminé ce mois.',
    totalServicos: 'Total de {n} service(s) :',
    pgOutro: 'Autres',
    mesJan: 'Jan', mesFev: 'Fév', mesMar: 'Mar', mesAbr: 'Avr', mesMai: 'Mai', mesJun: 'Juin',
    mesJul: 'Juil', mesAgo: 'Août', mesSet: 'Sep', mesOut: 'Oct', mesNov: 'Nov', mesDez: 'Déc',
    mesJanL: 'Janvier', mesFevL: 'Février', mesMarL: 'Mars', mesAbrL: 'Avril', mesMaiL: 'Mai', mesJunL: 'Juin',
    mesJulL: 'Juillet', mesAgoL: 'Août', mesSetL: 'Septembre', mesOutL: 'Octobre', mesNovL: 'Novembre', mesDezL: 'Décembre',
  },

  // ──────────────────────────────── عربي ──────────────────────────────────
  ar: {
    painel: 'لوحة التحكم', agendamentos: 'المواعيد', servicos: 'الخدمات',
    profissionais: 'المهنيون', clientes: 'العملاء', faturamento: 'الفواتير',
    configuracoes: 'الإعدادات', sair: 'تسجيل الخروج', copiarLink: 'نسخ الرابط',
    estabelecimento: 'المنشأة', voltar: 'رجوع →', carregando: 'جارٍ التحميل...',
    excluir: 'حذف', cancelar: 'إلغاء', confirmar: 'تأكيد', cancelarAcao: 'إلغاء',
    salvando: 'جارٍ الحفظ...',
    salvar: 'حفظ الإعدادات', sucesso: '✓ تم حفظ الإعدادات بنجاح!',
    infoBasicas: 'المعلومات الأساسية', horarioFunc: 'ساعات العمل',
    aparencia: 'المظهر واللغة', modoEscuro: 'الوضع الداكن', idioma: 'اللغة',
    nomeEstab: 'اسم المنشأة', linkAgend: 'رابط الحجز',
    telefone: 'الهاتف', descricao: 'الوصف', diasAtend: 'أيام العمل',
    abertura: 'الافتتاح', fechamento: 'الإغلاق',
    servicosSubtitle: 'إدارة خدمات منشأتك',
    novoServico: '+ خدمة جديدة', novoServicoTitulo: 'خدمة جديدة',
    nomeServico: 'اسم الخدمة *', descricaoOpcional: 'الوصف',
    duracaoLabel: 'المدة *', precoLabel: 'السعر *',
    placeholderServico: 'مثال: قص الشعر', placeholderDescricao: 'وصف اختياري',
    placeholderPreco: 'مثال: 50.00', salvarServico: 'حفظ الخدمة',
    nenhumServico: 'لا توجد خدمات مسجلة',
    nenhumServicoDesc: 'انقر على "خدمة جديدة" للإضافة.',
    erroPreencherCampos: 'يرجى ملء جميع الحقول المطلوبة.',
    erroConfigurarEstab: 'قم بإعداد منشأتك أولاً.',
    erroSalvarServico: 'خطأ في حفظ الخدمة.',
    profissionaisSubtitle: 'إدارة فريقك',
    novoProfissional: '+ مهني جديد', novoProfissionalTitulo: 'مهني جديد',
    foto: 'الصورة', fotoCliqueAdicionar: 'انقر للإضافة', fotoRemover: 'إزالة',
    nomeLabel: 'الاسم *', descricaoVisivelCliente: 'الوصف',
    descricaoVisivelClienteHint: '— مرئي للعميل',
    salvarProfissional: 'حفظ المهني',
    nenhumProfissional: 'لا يوجد مهنيون مسجلون',
    nenhumProfissionalDesc: 'انقر على "+ مهني جديد" للإضافة.',
    semDescricao: 'بدون وصف',
    fotoAdicionada: '✓ تمت إضافة الصورة · انقر على الصورة للتغيير',
    cliqueFoto: 'انقر على الصورة الرمزية لإضافة صورة', cliqueTrocarFoto: 'انقر لتغيير الصورة',
    erroNomeProfissional: 'أدخل اسم المهني.',
    erroEnviarFoto: 'خطأ في رفع الصورة: ', erroSalvarFoto: 'خطأ في حفظ الصورة: ',
    confirmarExcluir: 'هل أنت متأكد من حذف هذا المهني؟',
    planoAtivadoTitulo: 'تم تفعيل خطة Pro بنجاح!',
    planoAtivadoDesc: 'تم إلغاء تأمين المواعيد غير المحدودة. استمتع!',
    limiteAtingido: 'لقد وصلت إلى حد الخطة المجانية',
    agendamentosRestantes: 'لديك {n} موعد(مواعيد) مجاني متبقية',
    assinarDesc: 'اشترك في خطة Pro بـ <strong style="color:#00C27C">R$49,90/شهر</strong> واحصل على مواعيد غير محدودة',
    assinarAgora: '💳 اشترك الآن — R$49,90/شهر', redirecionando: 'جارٍ التحويل...',
    planoProAtivo: 'خطة Pro نشطة',
    ola: 'مرحباً، {nome}! 👋', bemVindo: 'أهلاً وسهلاً! 👋',
    resumoHoje: 'إليك ملخص منشأتك اليوم.',
    agendamentosHoje: 'مواعيد اليوم', clientesCadastrados: 'العملاء المسجلون',
    faturamentoMes: 'إيرادات الشهر', aguardandoConfirmacao: 'في انتظار التأكيد',
    seuLink: 'رابط الحجز الخاص بك', linkCopiado: 'تم نسخ الرابط!',
    copiar: 'نسخ', verPagina: 'عرض الصفحة',
    agendamentosSubtitle: 'إدارة جميع مواعيد منشأتك',
    filtroTodos: 'الكل', filtroPendentes: 'قيد الانتظار', filtroConfirmados: 'مؤكد',
    filtroConcluidos: 'مكتمل', filtroCancelados: 'ملغى',
    nenhumAgendamento: 'لا توجد مواعيد',
    nenhumAgendamentoDesc: 'شارك رابطك لبدء استقبال المواعيد.',
    concluir: 'إكمال', as: 'الساعة',
    pgDinheiro: 'نقدًا', pgPix: 'Pix', pgCartao: 'بطاقة',
    confirmarExcluirAgend: 'هل أنت متأكد من حذف هذا الموعد؟',
        confirmarExcluirAgendFaturamento: 'سيتم حذف هذا الموعد وخصم المبلغ من الإيرادات. تأكيد؟',
    // Clientes
    buscarCliente: 'البحث عن عميل...', clienteSingular: 'عميل', clientePlural: 'عملاء',
    clientesCadastradosLabel: 'مسجل(ون)', nenhumClienteEncontrado: 'لم يتم العثور على عملاء',
    nenhumClienteEncontradoDesc: 'حاول البحث باسم أو بريد إلكتروني آخر.',
    nenhumClienteAinda: 'لا يوجد عملاء بعد',
    nenhumClienteAindaDesc: 'سيظهر العملاء هنا عند حجز المواعيد.',
    agendamentoSingular: 'موعد', agendamentoPlural: 'مواعيد', gastos: 'أُنفق',
        confirmarExcluirCliente: 'هل أنت متأكد من حذف العميل "{nome}"؟',
    // Faturamento
    faturamentoSubtitle: 'تتبع إيراداتك شهرًا بشهر',
    total12Meses: 'إجمالي آخر 12 شهرًا', melhorMes: 'أفضل شهر', vsMesAnterior: 'مقابل الشهر السابق',
    faturamentoPorMes: 'الإيرادات حسب الشهر',
    legendaSelecionado: 'محدد', legendaMesAtual: 'الشهر الحالي', legendaMesesAnteriores: 'الأشهر السابقة',
    pagamentosMes: 'المدفوعات — {mes}', pagamentosMesDesc: 'كيف دفع العملاء هذا الشهر',
    pagamentosGeral: 'المدفوعات — آخر 12 شهرًا', pagamentosGeralDesc: 'نظرة عامة على جميع طرق الدفع',
    semPagamentosMes: 'لا توجد مدفوعات هذا الشهر.', semPagamentosGeral: 'لا توجد مدفوعات مسجلة.',
    semDados: 'لا توجد بيانات', pagamentos: 'دفعة',
    agendamentosConcluidos: 'موعد(مواعيد) مكتمل(ة)', totalDoMes: 'إجمالي الشهر',
    nenhumAgendamentoConcluido: 'لا توجد مواعيد مكتملة هذا الشهر.',
    totalServicos: 'إجمالي {n} خدمة:',
    pgOutro: 'أخرى',
    mesJan: 'يناير', mesFev: 'فبراير', mesMar: 'مارس', mesAbr: 'أبريل', mesMai: 'مايو', mesJun: 'يونيو',
    mesJul: 'يوليو', mesAgo: 'أغسطس', mesSet: 'سبتمبر', mesOut: 'أكتوبر', mesNov: 'نوفمبر', mesDez: 'ديسمبر',
    mesJanL: 'يناير', mesFevL: 'فبراير', mesMarL: 'مارس', mesAbrL: 'أبريل', mesMaiL: 'مايو', mesJunL: 'يونيو',
    mesJulL: 'يوليو', mesAgoL: 'أغسطس', mesSetL: 'سبتمبر', mesOutL: 'أكتوبر', mesNovL: 'نوفمبر', mesDezL: 'ديسمبر',
  },

  // ─────────────────────────────── 日本語 ──────────────────────────────────
  ja: {
    painel: 'ダッシュボード', agendamentos: '予約', servicos: 'サービス',
    profissionais: 'スタッフ', clientes: 'お客様', faturamento: '売上',
    configuracoes: '設定', sair: 'ログアウト', copiarLink: 'リンクをコピー',
    estabelecimento: '店舗', voltar: '← 戻る', carregando: '読み込み中...',
    excluir: '削除', cancelar: 'キャンセル', confirmar: '確認', cancelarAcao: 'キャンセル',
    salvando: '保存中...',
    salvar: '設定を保存', sucesso: '✓ 設定が正常に保存されました！',
    infoBasicas: '基本情報', horarioFunc: '営業時間',
    aparencia: '外観と言語', modoEscuro: 'ダークモード', idioma: '言語',
    nomeEstab: '店舗名', linkAgend: '予約リンク',
    telefone: '電話番号', descricao: '説明', diasAtend: '営業日',
    abertura: '開店', fechamento: '閉店',
    servicosSubtitle: '店舗のサービスを管理する',
    novoServico: '＋ 新しいサービス', novoServicoTitulo: '新しいサービス',
    nomeServico: 'サービス名 *', descricaoOpcional: '説明',
    duracaoLabel: '所要時間 *', precoLabel: '料金 *',
    placeholderServico: '例：ヘアカット', placeholderDescricao: '説明（任意）',
    placeholderPreco: '例：50.00', salvarServico: 'サービスを保存',
    nenhumServico: 'サービスが登録されていません',
    nenhumServicoDesc: '「新しいサービス」をクリックして追加してください。',
    erroPreencherCampos: '必須項目をすべて入力してください。',
    erroConfigurarEstab: '先に店舗を設定してください。',
    erroSalvarServico: 'サービスの保存中にエラーが発生しました。',
    profissionaisSubtitle: 'チームを管理する',
    novoProfissional: '＋ 新しいスタッフ', novoProfissionalTitulo: '新しいスタッフ',
    foto: '写真', fotoCliqueAdicionar: 'クリックして追加', fotoRemover: '削除',
    nomeLabel: '名前 *', descricaoVisivelCliente: '説明',
    descricaoVisivelClienteHint: '— お客様に表示されます',
    salvarProfissional: 'スタッフを保存',
    nenhumProfissional: 'スタッフが登録されていません',
    nenhumProfissionalDesc: '「＋ 新しいスタッフ」をクリックして追加してください。',
    semDescricao: '説明なし',
    fotoAdicionada: '✓ 写真追加済み · アバターをクリックして変更',
    cliqueFoto: 'アバターをクリックして写真を追加', cliqueTrocarFoto: 'クリックして写真を変更',
    erroNomeProfissional: 'スタッフの名前を入力してください。',
    erroEnviarFoto: '写真のアップロードエラー: ', erroSalvarFoto: '写真の保存エラー: ',
    confirmarExcluir: 'このスタッフを削除してもよろしいですか？',
    planoAtivadoTitulo: 'Proプランが正常に有効化されました！',
    planoAtivadoDesc: '無制限の予約が解放されました。お楽しみください！',
    limiteAtingido: '無料プランの上限に達しました',
    agendamentosRestantes: '残り{n}件の無料予約があります',
    assinarDesc: 'Proプランに<strong style="color:#00C27C">R$49,90/月</strong>でサブスクライブして無制限の予約を取得',
    assinarAgora: '💳 今すぐサブスクライブ — R$49,90/月', redirecionando: 'リダイレクト中...',
    planoProAtivo: 'Proプラン有効',
    ola: 'こんにちは、{nome}さん！ 👋', bemVindo: 'ようこそ！ 👋',
    resumoHoje: '今日の店舗の概要です。',
    agendamentosHoje: '今日の予約', clientesCadastrados: '登録済みお客様',
    faturamentoMes: '今月の売上', aguardandoConfirmacao: '確認待ち',
    seuLink: '予約リンク', linkCopiado: 'リンクをコピーしました！',
    copiar: 'コピー', verPagina: 'ページを表示',
    agendamentosSubtitle: '店舗のすべての予約を管理する',
    filtroTodos: 'すべて', filtroPendentes: '保留中', filtroConfirmados: '確認済み',
    filtroConcluidos: '完了', filtroCancelados: 'キャンセル済み',
    nenhumAgendamento: '予約がありません',
    nenhumAgendamentoDesc: 'リンクを共有して予約を受け付けてください。',
    concluir: '完了にする', as: '時',
    pgDinheiro: '現金', pgPix: 'Pix', pgCartao: 'カード',
    confirmarExcluirAgend: 'この予約を削除してもよろしいですか？',
        confirmarExcluirAgendFaturamento: 'この予約を削除すると売上から差し引かれます。確認しますか？',
    // Clientes
    buscarCliente: 'お客様を検索...', clienteSingular: 'お客様', clientePlural: 'お客様',
    clientesCadastradosLabel: '登録済み', nenhumClienteEncontrado: 'お客様が見つかりません',
    nenhumClienteEncontradoDesc: '別の名前またはメールで検索してください。',
    nenhumClienteAinda: 'まだお客様がいません',
    nenhumClienteAindaDesc: '予約が入るとここに表示されます。',
    agendamentoSingular: '件の予約', agendamentoPlural: '件の予約', gastos: '使用済み',
        confirmarExcluirCliente: 'お客様「{nome}」を削除してもよろしいですか？',
    // Faturamento
    faturamentoSubtitle: '月ごとの売上を追跡する',
    total12Meses: '過去12ヶ月の合計', melhorMes: '最高月', vsMesAnterior: '前月比',
    faturamentoPorMes: '月別売上',
    legendaSelecionado: '選択中', legendaMesAtual: '今月', legendaMesesAnteriores: '過去の月',
    pagamentosMes: '支払い — {mes}', pagamentosMesDesc: '今月の支払い方法',
    pagamentosGeral: '支払い — 過去12ヶ月', pagamentosGeralDesc: 'すべての支払い方法の概要',
    semPagamentosMes: '今月の支払いはありません。', semPagamentosGeral: '支払いが登録されていません。',
    semDados: 'データなし', pagamentos: '件',
    agendamentosConcluidos: '件の予約完了', totalDoMes: '月合計',
    nenhumAgendamentoConcluido: '今月完了した予約はありません。',
    totalServicos: '{n}件のサービス合計:',
    pgOutro: 'その他',
    mesJan: '1月', mesFev: '2月', mesMar: '3月', mesAbr: '4月', mesMai: '5月', mesJun: '6月',
    mesJul: '7月', mesAgo: '8月', mesSet: '9月', mesOut: '10月', mesNov: '11月', mesDez: '12月',
    mesJanL: '1月', mesFevL: '2月', mesMarL: '3月', mesAbrL: '4月', mesMaiL: '5月', mesJunL: '6月',
    mesJulL: '7月', mesAgoL: '8月', mesSetL: '9月', mesOutL: '10月', mesNovL: '11月', mesDezL: '12月',
  },
}

interface PreferencesContextType {
  darkMode: boolean
  setDarkMode: (v: boolean) => void
  idioma: Idioma
  setIdioma: (v: Idioma) => void
  t: (key: string) => string
}

const PreferencesContext = createContext<PreferencesContextType>({
  darkMode: false, setDarkMode: () => {}, idioma: 'pt', setIdioma: () => {}, t: (k) => k,
})

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [darkMode, setDarkModeState] = useState(false)
  const [idioma, setIdiomaState] = useState<Idioma>('pt')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    const savedDark   = localStorage.getItem('darkMode') === 'true'
    const savedIdioma = (localStorage.getItem('idioma') as Idioma) || 'pt'
    setDarkModeState(savedDark)
    setIdiomaState(savedIdioma)
    setMounted(true)
  }, [])

  useEffect(() => {
    if (!mounted) return
    document.documentElement.setAttribute('data-theme', darkMode ? 'dark' : 'light')
    localStorage.setItem('darkMode', String(darkMode))
  }, [darkMode, mounted])

  useEffect(() => {
    if (!mounted) return
    localStorage.setItem('idioma', idioma)
    document.documentElement.setAttribute('lang', idioma)
    document.documentElement.setAttribute('dir', idioma === 'ar' ? 'rtl' : 'ltr')
  }, [idioma, mounted])

  function setDarkMode(v: boolean) { setDarkModeState(v) }
  function setIdioma(v: Idioma) { setIdiomaState(v) }
  function t(key: string) { return TRADUCOES[idioma]?.[key] ?? TRADUCOES['pt'][key] ?? key }

  if (!mounted) return <>{children}</>

  return (
    <PreferencesContext.Provider value={{ darkMode, setDarkMode, idioma, setIdioma, t }}>
      {children}
    </PreferencesContext.Provider>
  )
}

export function usePreferences() {
  return useContext(PreferencesContext)
}